sudo: required
services:
- docker
language: java
dist: trusty
jdk:
- openjdk8
cache:
directories:
- $HOME/.m2
script:
- mvn clean package -U
- docker build -t kr3037/simpleshift-locations .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push kr3037/simpleshift-locations