kumuluzee:
  server:
    base-url: http://localhost:8081
    http:
      port: 8081

  name: locations-service
  version: 1.0.0
  env:
    name: dev

  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://159.122.187.27:32132

  discovery:
    etcd:
      hosts: http://159.122.187.27:32132
    ttl: 20
    ping-interval: 15

    metrics:
      web-instrumentation:
      - name: locations-endpoint
        url-pattern: /v1/locations/*

app-properties:
  external-services:
    enabled: true