apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations
  template:
    metadata:
      labels:
        app: locations
    spec:
      containers:
      - image: kr3037/simpleshift-locations:latest
        name: locations
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: locations
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: locations