apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations
  template:
    metadata:
      labels:
        app: locations
    spec:
      containers:
      - image: kr3037/simpleshift-locations:0.06
        name: locations
        env:
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_ENV_NAME
          value: kum
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP